Update pylint_sphinx_workflow.yml

diff --git a/.github/workflows/pylint_sphinx_workflow.yml b/.github/workflows/pylint_sphinx_workflow.yml
--- a/.github/workflows/pylint_sphinx_workflow.yml
+++ b/.github/workflows/pylint_sphinx_workflow.yml
@@ -31,19 +31,17 @@ jobs:
       env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
-        BASE_BRANCH=${{ github.base_ref }}  # Get the base branch of the PR
-        git fetch origin $BASE_BRANCH  # Ensure the base branch is available
-        git checkout $BASE_BRANCH  # Switch to the base branch
-        git checkout -  # Return to the detached HEAD state
-        gh pr diff --name-only | grep ".py$" > modFiles.txt
+        git fetch origin "+refs/pull/${{ github.event.pull_request.number }}/merge:refs/remotes/origin/pr/${{ github.event.pull_request.number }}"
+        git checkout refs/remotes/origin/pr/${{ github.event.pull_request.number }}
+        gh pr diff --name-only | grep ".py$" > modFiles.txt || true  # Avoid failure if no Python files are changed
+        
         echo "files=$(cat modFiles.txt | tr '\n' ' ')" >> $GITHUB_OUTPUT
-
-    - name: Run Ruff linting
-      if: steps.changed-files.outputs.files != ''
-      run: |
-        for file in $(cat modFiles.txt); do
-          ruff check $file --config ./pyproject.toml || exit 1
-        done
+        - name: Run Ruff linting
+          if: steps.changed-files.outputs.files != ''
+          run: |
+            for file in $(cat modFiles.txt); do
+              ruff check $file --config ./pyproject.toml || exit 1
+            done
 
     - name: Build documentation
       if: steps.changed-files.outputs.files != ''
